"use strict";
exports.__esModule = true;
var Arraylist_1 = require("./Arraylist");
var Linkedlist_1 = require("./Linkedlist");
var myArraylist = new Arraylist_1["default"]([1, 2, 3]);
console.log(myArraylist.getSize());
var myLinkedlist = new Linkedlist_1["default"]([1, 2, 3]);
console.log(myLinkedlist.getSize());
console.log(myLinkedlist.clear());
console.log(myLinkedlist.getSize());
